### PR TITLE
fix!: add GovVoteDecorator

### LINKED ISSUE #2910: Attackers can perform an inexpensive DoS attack by spamming Vote transactions
# Problem

The issue was discovered during the [Oak Security audit of SDK 0.47](https://twitter.com/SecurityOak/status/1749834440451178862) -- see issue 10.  

# Closing criteria

Add antehandler to not allow accounts that do not possess a minimum amount of staked coins to vote

# Problem details

See audit report.

### PR DESCRIPTION
**Pull request by mpoke**
## Description

Closes: #2910

Add ante handler that allows `MsgVote` from accounts with at least 1 atom staked. 

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

* [x] Included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [x] Added `!` to the type prefix if API, client, or state breaking change (i.e., requires minor or major version bump)
* [x] Targeted the correct branch (see [PR Targeting](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
* [x] Provided a link to the relevant issue or specification
* [x] Followed the guidelines for [building SDK modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules)
* [x] Included the necessary unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
* [x] Added a changelog entry in `.changelog` (for details, see [contributing guidelines](../../CONTRIBUTING.md#changelog))
* [x] Included comments for [documenting Go code](https://blog.golang.org/godoc)
* [ ] Updated the relevant documentation or specification
* [x] Reviewed "Files changed" and left comments if necessary 
* [ ] Confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

* [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] confirmed `!` in the type prefix if API or client breaking change
* [ ] confirmed all author checklist items have been addressed 
* [ ] reviewed state machine logic
* [ ] reviewed API design and naming
* [ ] reviewed documentation is accurate
* [ ] reviewed tests and test coverage

### CODE REVIEW

File: ante/gov_vote_ante.go [hunk 1]
```diff
@@ -0,0 +1,116 @@
...
+	"github.com/cosmos/cosmos-sdk/x/authz"
+	govv1beta1 "github.com/cosmos/cosmos-sdk/x/gov/types/v1beta1"
+	stakingkeeper "github.com/cosmos/cosmos-sdk/x/staking/keeper"
+	stakingtypes "github.com/cosmos/cosmos-sdk/x/staking/types"
+
+	gaiaerrors "github.com/cosmos/gaia/v15/types/errors"
+)
+
+var (
+	minStakedTokens       = sdk.NewDec(1000000) // 1000.000 uatom (or 1 atom)
```
Comment (MSalopek) [inline ante/gov_vote_ante.go]:
```suggestion
	minStakedTokens       = sdk.NewDec(1000000) // 1_000_000 uatom (or 1 atom)
```

Confusing to read. Could not tell if you added zeros after the decimal point by accident.

**Review by MSalopek — APPROVED** [review]
LGTM!

Left some nits

**Comment by sainoe** [comment]
LGTM!

**Review by sainoe — APPROVED** [review]
