### PR TITLE
fix:  Removal of liquidity module

### LINKED ISSUE #2714: Remove liquidity
# Problem

Gaia v11 removed the state of the Liquidity module, but the module is still part of the Gaia binary.

# Closing criteria

The liquidity module is removed

### PR DESCRIPTION
**Pull request by bermuell**
## Description

Closes: #2714

Removal of the liquidty staking module as since there is no depency after state removal done in v11

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

* [x] Included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [x] Added `!` to the type prefix if API, client, or state breaking change (i.e., requires minor or major version bump)
* [x] Targeted the correct branch (see [PR Targeting](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
* [x] Provided a link to the relevant issue or specification
* [ ] Followed the guidelines for [building SDK modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules)
* [ ] Included the necessary unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
* [x] Added a changelog entry in `.changelog` (for details, see [contributing guidelines](../../CONTRIBUTING.md#changelog))
* [x] Included comments for [documenting Go code](https://blog.golang.org/godoc)
* [ ] Updated the relevant documentation or specification
* [x] Reviewed "Files changed" and left comments if necessary 
* [x] Confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

* [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] confirmed `!` in the type prefix if API or client breaking change
* [ ] confirmed all author checklist items have been addressed 
* [ ] reviewed state machine logic
* [ ] reviewed API design and naming
* [ ] reviewed documentation is accurate
* [ ] reviewed tests and test coverage

### CODE REVIEW

File: app/app.go [hunk 1]
```diff
@@ -356,6 +356,7 @@ func (app *GaiaApp) setupUpgradeStoreLoaders() {
 	}
 
 	for _, upgrade := range Upgrades {
+		upgrade := upgrade
```
Comment (bermuell) [inline app/app.go:359]: This fixes a linter error ('G601: Implicit memory aliasing in for loop. (gosec)'

File: go.mod
Comment (mpoke) [inline go.mod:1]: `go.sum` missing; please run `go mod tidy`

**Review by mpoke — CHANGES_REQUESTED** [review]
Please rebase to main. This changes will go in the next release, i.e., v13.

File: .changelog/v11.0.0/dependencies/2652-liquidity-removal.md
Comment (mpoke) [inline .changelog/v11.0.0/dependencies/2652-liquidity-removal.md:1]: Move to `.changelog/unreleased/...`.

File: .changelog/v11.0.0/state-breaking/2652-liquidity-removal.md
Comment (mpoke) [inline .changelog/v11.0.0/state-breaking/2652-liquidity-removal.md:1]: Move to `.changelog/unreleased/...`.

**Review by mpoke — CHANGES_REQUESTED** [review]

File: .changelog/v11.0.0/state-breaking/2652-liquidity-removal.md
Comment (bermuell) [reply .changelog/v11.0.0/state-breaking/2652-liquidity-removal.md:1]: Will revert the changes on .changelog/v11.0.0 as PR is targeting 'main' now
Since we're targeting this for 'main' branch, is the removal of v1.6.0-forced-withdrawal to be considered "state braking"?  as there is no state dependency for liquidity anymore and the related state breaking was announced in v11.x release?

Comment (mpoke) [reply .changelog/v11.0.0/state-breaking/2652-liquidity-removal.md:1]: That makes sense. Since the state was already removed, I don't think it's state breaking.

**Review by mpoke — APPROVED** [review]
Nice work @bermuell.

**Review by yaruwangway — APPROVED** [review]

**Comment by Frankoxt** [comment]
> 
> 
> ## Description
> 
> Closes: #2714
> 
> Removal of the liquidty staking module as since there is no depency after state removal done in v11
> 
> ### Author Checklist
> 
> *All items are required. Please add a note to the item if the item is not applicable and
> please add links to any relevant follow up issues.*
> 
> I have...
> 
> * [x] Included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
> * [x] Added `!` to the type prefix if API, client, or state breaking change (i.e., requires minor or major version bump)
> * [x] Targeted the correct branch (see [PR Targeting](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
> * [x] Provided a link to the relevant issue or specification
> * [ ] Followed the guidelines for [building SDK modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules)
> * [ ] Included the necessary unit and integration [tests](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#testing)
> * [x] Added a changelog entry in `.changelog` (for details, see [contributing guidelines](../../CONTRIBUTING.md#changelog))
> * [x] Included comments for [documenting Go code](https://blog.golang.org/godoc)
> * [ ] Updated the relevant documentation or specification
> * [x] Reviewed "Files changed" and left comments if necessary 
> * [x] Confirmed all CI checks have passed
> 
> ### Reviewers Checklist
> 
> *All items are required. Please add a note if the item is not applicable and please add
> your handle next to the items reviewed if you only reviewed selected items.*
> 
> I have...
> 
> * [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
> * [ ] confirmed `!` in the type prefix if API or client breaking change
> * [ ] confirmed all author checklist items have been addressed 
> * [ ] reviewed state machine logic
> * [ ] reviewed API design and naming
> * [ ] reviewed documentation is accurate
> * [ ] reviewed tests and test coverage
>
