### PR TITLE
Fix: use `bondDenom` as default globalfee denom

### LINKED ISSUE #1823: test issues of hard coded global fee denom
## Summary of Bug
The default global fee is using a hardcoded denom `uatom`.
This works only for the hub, but for users who want to use gaiad for tests, tests will fail if the chain is not inited with a denom `uatom`.

## Steps to Reproduce
- init a chain by`gaiad init` (the default chain is using denom `stake`)
- submit transactions with paying fee in `stake`, test will fail.

## Fix

config `bondDenom` in staking params as default global fee denom if globalfee is empty.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

### PR DESCRIPTION
**Pull request by yaruwangway**
## Fix: use `bondDenom` in staking module of the denom of defalut global fee.
closes: #1823

To fix issue #1823, stakingParams will be added to `FeeDecorator` for antehandler to access bondDnom. Default globalfee is configured the same as the chain's bonddenom, rather than hardcoded `uatom`

### CODE REVIEW

File: ante/ante.go [hunk 1]
```diff
@@ -36,6 +37,9 @@ func NewAnteHandler(opts HandlerOptions) (sdk.AnteHandler, error) {
 	if opts.GlobalFeeSubspace.Name() == "" {
 		return nil, sdkerrors.Wrap(sdkerrors.ErrLogic, "param store is required for ante builder")
 	}
+	if opts.StakingSubspace.Name() == "" {
+		return nil, sdkerrors.Wrap(sdkerrors.ErrLogic, "param store is required for ante builder")
```
Comment (Pantani) [inline ante/ante.go]:
```suggestion
		return nil, sdkerrors.Wrap(sdkerrors.ErrLogic, "staking param store is required for ante builder")
```

File: ante/ante.go [hunk 2]
```diff
@@ -36,6 +37,9 @@ func NewAnteHandler(opts HandlerOptions) (sdk.AnteHandler, error) {
 	if opts.GlobalFeeSubspace.Name() == "" {
 		return nil, sdkerrors.Wrap(sdkerrors.ErrLogic, "param store is required for ante builder")
```
Comment (Pantani) [inline ante/ante.go]:
```suggestion
		return nil, sdkerrors.Wrap(sdkerrors.ErrLogic, "global fee param store is required for ante builder")
```

File: x/globalfee/ante/antetest/fee_test_setup.go [hunk 3]
```diff
@@ -54,6 +55,12 @@ func (s *IntegrationTestSuite) SetupTestGlobalFeeStoreAndMinGasPrice(minGasPrice
 	return subspace
 }
 
+// in the fee test, set uatom as bond denom.
```
Comment (Pantani) [inline x/globalfee/ante/antetest/fee_test_setup.go]:
```suggestion
// SetupTestStakingSubspace sets uatom as bond denom for the fee tests.
```

File: x/globalfee/ante/fee_utils.go [hunk 4]
```diff
@@ -31,6 +32,24 @@ func (mfd FeeDecorator) getGlobalFee(ctx sdk.Context, feeTx sdk.FeeTx) sdk.Coins
 	return requiredGlobalFees.Sort()
 }
 
+func (mfd FeeDecorator) DefaultZeroGlobalFee(ctx sdk.Context) []sdk.DecCoin {
+	bondDenom := mfd.getBondDenom(ctx)
+	if bondDenom == "" { //todo: check bonddenom is only one denom
```
Comment (Pantani) [inline x/globalfee/ante/fee_utils.go]: The lint is complaining, maybe we should add the TODO comment above the `if`.

**Review by Pantani — APPROVED** [review]

File: ante/ante.go (hunk 1 above)
Comment (Pantani) [reply ante/ante.go]: also, instead return `sdkerrors.ErrLogic` we can create new custom errors for Gaia, like `gaiaerrors.ErrSubspaceNotFound`

Comment (yaruwangway) [reply ante/ante.go]: shall we use `sdk.ErrNotFound` instead?

File: x/globalfee/ante/antetest/fee_test_setup.go (hunk 3 above)
Comment (yaruwangway) [reply x/globalfee/ante/antetest/fee_test_setup.go]: shall we use `sdk.ErrNotFound` instead?

File: ante/ante.go (hunk 1 above)
Comment (yaruwangway) [reply ante/ante.go]: actually sdk uses `ErrLogic` in [ this situation](https://github.com/cosmos/cosmos-sdk/blob/18d8b64ce596131b986a96bfa44524cb9625970b/x/auth/ante/ante.go#L27).

File: x/globalfee/ante/fee_utils.go [hunk 5]
```diff
@@ -31,6 +32,25 @@ func (mfd FeeDecorator) getGlobalFee(ctx sdk.Context, feeTx sdk.FeeTx) sdk.Coins
 	return requiredGlobalFees.Sort()
 }
 
+func (mfd FeeDecorator) DefaultZeroGlobalFee(ctx sdk.Context) []sdk.DecCoin {
+	bondDenom := mfd.getBondDenom(ctx)
+	// todo: check bonddenom is only one denom
+	if bondDenom == "" {
+		panic("staking bond denom is empty")
```
Comment (Pantani) [inline x/globalfee/ante/fee_utils.go]: Can we return an error and use `s.T().Fatalf(err)` in the parent method?

**Review by Pantani — APPROVED** [review]
LGTM. Only a one suggestions

File: x/globalfee/ante/fee_utils.go (hunk 5 above)
Comment (yaruwangway) [reply x/globalfee/ante/fee_utils.go]: Hi, you meant not panic in `DefaultZeroGlobalFee`, but return error `func (mfd FeeDecorator) DefaultZeroGlobalFee(ctx sdk.Context) ([]sdk.DecCoin, error)`, and then panic [here](https://github.com/cosmos/gaia/blob/b0b59461682a10c920646e65faed2c82d019f066/x/globalfee/ante/fee_utils.go#L21) if err ?

Comment (Pantani) [reply x/globalfee/ante/fee_utils.go]: yess!!! WDYT? This will be more clear to debug in the test logs

File: x/globalfee/ante/antetest/fee_test.go [hunk 6]
```diff
@@ -19,6 +19,22 @@ func TestIntegrationTestSuite(t *testing.T) {
...
+func (s *IntegrationTestSuite) TestGetDefaultGlobalFees() {
+	bondDenom := "uatom"
+	// set globalfees and min gas price
+	globalfeeSubspace := s.SetupTestGlobalFeeStoreAndMinGasPrice([]sdk.DecCoin{}, &globfeetypes.Params{})
+	stakingSubspace := s.SetupTestStakingSubspace(bondDenom)
+	// setup antehandler
+	mfd := gaiafeeante.NewFeeDecorator(gaiaapp.GetDefaultBypassFeeMessages(), globalfeeSubspace, stakingSubspace)
+
+	defaultGlobalFees, err := mfd.DefaultZeroGlobalFee(s.ctx)
+	s.Require().NoError(err)
```
Comment (Pantani) [inline x/globalfee/ante/antetest/fee_test.go:37]:
```suggestion
	s.Require().NoError(err)
	s.Require().Greater(len(defaultGlobalFees), 0)
```

File: x/globalfee/ante/fee.go [hunk 7]
```diff
@@ -97,3 +101,47 @@ func (mfd FeeDecorator) AnteHandle(ctx sdk.Context, tx sdk.Tx, simulate bool, ne
...
+	var globalMinGasPrices sdk.DecCoins
+	var err error
+	if mfd.GlobalMinFee.Has(ctx, types.ParamStoreKeyMinGasPrices) {
+		mfd.GlobalMinFee.Get(ctx, types.ParamStoreKeyMinGasPrices, &globalMinGasPrices)
+	}
+	// global fee is empty set, set global fee to 0uatom
+	if len(globalMinGasPrices) == 0 {
+		globalMinGasPrices, err = mfd.DefaultZeroGlobalFee(ctx)
+		if err != nil {
+			panic(err)
```
Comment (Pantani) [inline x/globalfee/ante/fee.go]: IMHO we should avoid panic in the helper method, the panic should stay in the first layer of the code or use test fail. But it is something we should create an issue to try to handle panics from the code and merge this PR as is

File: x/globalfee/ante/fee.go [hunk 8]
```diff
@@ -97,3 +101,47 @@ func (mfd FeeDecorator) AnteHandle(ctx sdk.Context, tx sdk.Tx, simulate bool, ne
 
 	return next(ctx, tx, simulate)
 }
+
+// ParamStoreKeyMinGasPrices type require coins sorted. getGlobalFee will also return sorted coins (might return 0denom if globalMinGasPrice is 0)
+func (mfd FeeDecorator) getGlobalFee(ctx sdk.Context, feeTx sdk.FeeTx) sdk.Coins {
+	var globalMinGasPrices sdk.DecCoins
+	var err error
```
Comment (Pantani) [inline x/globalfee/ante/fee.go]:
```suggestion
	var (
		globalMinGasPrices sdk.DecCoins
		err error
	)
```

File: x/globalfee/ante/fee.go [hunk 9]
```diff
@@ -97,3 +101,47 @@ func (mfd FeeDecorator) AnteHandle(ctx sdk.Context, tx sdk.Tx, simulate bool, ne
...
+		requiredGlobalFees[i] = sdk.NewCoin(gp.Denom, fee.Ceil().RoundInt())
+	}
+
+	return requiredGlobalFees.Sort()
+}
+
+func (mfd FeeDecorator) DefaultZeroGlobalFee(ctx sdk.Context) ([]sdk.DecCoin, error) {
+	bondDenom := mfd.getBondDenom(ctx)
+	if bondDenom == "" {
+		return []sdk.DecCoin{}, errors.New("empty staking bond denomination")
```
Comment (Pantani) [inline x/globalfee/ante/fee.go]: avoid allocating a new slice into the memory if we are not using it

```suggestion
		return nil, errors.New("empty staking bond denomination")
```

File: x/globalfee/ante/antetest/fee_test_setup.go [hunk 10]
```diff
@@ -56,8 +56,8 @@ func (s *IntegrationTestSuite) SetupTestGlobalFeeStoreAndMinGasPrice(minGasPrice
 }
 
 // SetupTestStakingSubspace sets uatom as bond denom for the fee tests.
-func (s *IntegrationTestSuite) SetupTestStakingSubspace(bondDenom string) types.Subspace {
-	s.app.GetSubspace(stakingtypes.ModuleName).Set(s.ctx, stakingtypes.KeyBondDenom, bondDenom)
+func (s *IntegrationTestSuite) SetupTestStakingSubspace(params stakingtypes.Params) types.Subspace {
+	s.app.GetSubspace(stakingtypes.ModuleName).SetParamSet(s.ctx, &params)
 	return s.app.GetSubspace(stakingtypes.ModuleName)
```
Comment (yaruwangway) [inline x/globalfee/ante/antetest/fee_test_setup.go:61]: Hi  @Pantani,  I changed `set` to `SetParamSet `. in sdk, when using `setParamSet`, it will call a validate  function , which will validate if the `bondDenom` is empty, if empty, it will panic. 
this means in our app, when `init`, the staking bondDenom is not empty because `setParamSet` in the call stack of `init`.

so I m not sure now if I still check if bondDenom empty [here](https://github.com/cosmos/gaia/blob/ce9762e3bcbb69d7e08811767da4d522cfd39ae7/x/globalfee/ante/fee.go#L133)
extra checking is always ok ?

File: x/globalfee/ante/fee.go (hunk 7 above)
Comment (yaruwangway) [reply x/globalfee/ante/fee.go]: I changed the panic to antehandler now

**Review by okwme — APPROVED** [review]
