### PR TITLE
fix: all fees

### LINKED ISSUE #1528: Rho: make bypass fee and global fee compatible
## Summary
[bypass min fee](https://github.com/cosmos/gaia/blob/v7.0.2/ante/fee.go) allow config a certain types of msgs to skip fee check.
but Rho also will have another fee check antehandler: [global fee](https://github.com/confio/tgrade/tree/main/x/globalfee). 

Global fee should also allow bypass certain types of msgs set in the config. or allow config if allow bypass

## Proposal

write one antehandler to put all fee checks together: `min_gas_price` in app.toml and `globalfees` with bypass function.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

### PR DESCRIPTION
**Pull request by yaruwangway**
Close: #1528 
please see https://github.com/cosmos/gaia/pull/1604

### CODE REVIEW

**Comment by yaruwangway** [comment]
here is a doc might be helpful for reviewing this pr. https://github.com/cosmos/gaia/pull/1615

File: ante/fee.go [hunk 1]
```diff
@@ -15,13 +14,15 @@ import (
...
 // FeeWithBypassDecorator will check if the transaction's fee is at least as large
-// as the local validator's minimum gasFee (defined in validator config) and global fee.
+// as the local validator's minimum gasFee (defined in validator config) and global fee, and the fee denom should be in the global fees' denoms.
 //
 // If fee is too low, decorator returns error and tx is rejected from mempool.
 // Note this only applies when ctx.CheckTx = true. If fee is high enough or not
 // CheckTx, then call next AnteHandler.
 //
 // CONTRACT: Tx must implement FeeTx to use BypassMinFeeDecorator
+// If the tx msg type is one the bypass msg types, the tx is free from fee charge.
```
Comment (okwme) [inline ante/fee.go]:
```suggestion
// If the tx msg type is one of the bypass msg types, the tx is valid even if the min fee is lower than normally required.
```

File: ante/fee_utils.go [hunk 2]
```diff
@@ -0,0 +1,190 @@
...
+	for _, coin := range coinsB {
+		if coin.IsZero() {
+			return true
+		}
+	}
+
+	return false
+}
+
+// CombinedFeeRequirement will combine the global fee and min_gas_price. globalFees, minGasPrices must be valid, but CombinedFeeRequirement does not valid them.
```
Comment (okwme) [inline ante/fee_utils.go:145]:
```suggestion
// CombinedFeeRequirement will combine the global fee and min_gas_price. globalFees, minGasPrices must be valid, but CombinedFeeRequirement does not validate them.
```

File: ante/fee.go [hunk 3]
```diff
@@ -62,165 +64,48 @@ func (mfd BypassMinFeeDecorator) AnteHandle(ctx sdk.Context, tx sdk.Tx, simulate
...
 			requiredGlobalFees := mfd.getGlobalFee(ctx, feeTx)
-			if !DenomsSubsetOf(feeCoins, requiredGlobalFees) {
-				return ctx, sdkerrors.Wrapf(sdkerrors.ErrInsufficientFee, "fees %s is not a subset of required global fees %s", feeCoins, requiredGlobalFees)
-			}
-			// At least feeCoin amount must be greater than or equal to one of the requiredGlobalFees
-			if !IsAnyGTEIncludingZero(feeCoins, requiredGlobalFees) {
-				return ctx, sdkerrors.Wrapf(sdkerrors.ErrInsufficientFee, "insufficient fees for global fee; got: %s required: %s", feeCoins, requiredGlobalFees)
-			}
+			allFees = CombinedFeeRequirement(requiredGlobalFees, requiredFees)
+			fmt.Println("allfees:", allFees)
```
Comment (okwme) [inline ante/fee.go:80]:
```suggestion
```

File: ante/fee_utils.go [hunk 4]
```diff
@@ -0,0 +1,190 @@
...
+	for _, coin := range coinsB {
+		if coin.IsZero() {
+			return true
+		}
+	}
+
+	return false
+}
+
+// CombinedFeeRequirement will combine the global fee and min_gas_price. globalFees, minGasPrices must be valid, but CombinedFeeRequirement does not valid them so they may return 0denom.
```
Comment (glnro) [inline ante/fee_utils.go]:
```suggestion
// CombinedFeeRequirement will combine the global fee and min_gas_price. Both globalFees and minGasPrices must be valid, but CombinedFeeRequirement does not validate them so it may return 0denom.
```
