### PR TITLE
test: fix unsafe-start-local-validator command

### LINKED ISSUE #3372: upgrade mainnet forking tool to support provider endblocker changes
Tool stopped working on versions >= v20.0.0.

```
 gaiad testnet unsafe-start-local-validator  \
--validator-operator="cosmosvaloper1pazy2th7lz38pjlxgt6d72p82trkdlrqnh3ja7"  \
--validator-pubkey="x1T1PtozNbSZGZajD2S6/Lp0ObYvhzRcwxFDb2P6L+Y=" \
--validator-privkey="toUbarT3MwRqgakYVka4PNQKzIjTs3Ql8tqXRozWBuzHVPU+2jM1tJkZlqMPZLr8unQ5ti+HNFzDEUNvY/ov5g=="  \
--accounts-to-fund="cosmos1pazy2th7lz38pjlxgt6d72p82trkdlrqkr983d"
```

Seems related to cometbft v0.38.11 and higher versions.

The tool encounters a consensus failure with node snapshots:
```
2:52PM INF Replay: Vote blockID=C80F67CDC3EFDB6E3496605908EFBDEA0A73E58315E9B34A3491C3383702D8F4:1:5ED0B863FBFA extSigLen=0 extensionLen=0 height=22453073 module=consensus peer=7314c477c9d7fea4e2ebf51581f2324971260494 round=0 type=SIGNED_MSG_TYPE_PRECOMMIT
2:52PM INF failed attempting to add vote err="cannot find validator 151 in valSet of size 1: invalid validator index" module=consensus
2:52PM ERR failed to process message err="error adding vote" height=22453074 module=consensus msg_type=*consensus.VoteMessage peer=7314c477c9d7fea4e2ebf51581f2324971260494 round=0

2:52PM ERR CONSENSUS FAILURE!!! err="failed to apply block; error commit failed for application: changing validator set: failed to find validator 000001E443FD237E4B616E2FA69DF4EE3D49A94F to remove"
```

### PR DESCRIPTION
**Pull request by stana-miric**
Closes #3372 
unsafe-start-local-validator is updated with the code that clears provider state related to old validators

### CODE REVIEW

File: cmd/gaiad/cmd/testnet_set_local_validator.go [hunk 1]
```diff
@@ -266,6 +266,9 @@ func updateApplicationState(app *gaia.GaiaApp, args valArgs) error {
 
 	app.SlashingKeeper.SetValidatorSigningInfo(appCtx, newConsAddr, newValidatorSigningInfo)
 
+	// PROVIDER
+	app.ProviderKeeper.DeleteLastProviderConsensusValSet(appCtx)
+
 	shortVotingPeriod := time.Second * 20
```
Comment (dusan-maksimovic) [inline cmd/gaiad/cmd/testnet_set_local_validator.go:273]: The section below refers to the Gov module, right?

```suggestion
        // GOVERNANCE
	shortVotingPeriod := time.Second * 20
```

**Review by dusan-maksimovic — APPROVED** [review]
LGTM!

**Review by MSalopek — APPROVED** [review]
